/**
 * Mock data generator for testing without Keboola credentials.
 * Generates realistic table metadata for visual verification.
 */

export function generateMockMetadata() {
  const tables = [
    {
      id: 'out.c-bdm.REF_CLIENT',
      name: 'REF_CLIENT',
      description: 'Reference table for clients and customer master data',
      primaryKey: ['CLIENT_ID'],
      rowsCount: 15420,
      dataSizeBytes: 2457600,
      columnCount: 6,
      columns: [
        { name: 'CLIENT_ID', databaseNativeType: 'INTEGER', keboolaBaseType: 'INTEGER', nullable: false, description: 'Unique client identifier', length: null },
        { name: 'CLIENT_NAME', databaseNativeType: 'VARCHAR(255)', keboolaBaseType: 'STRING', nullable: false, description: 'Full client name', length: '255' },
        { name: 'EMAIL', databaseNativeType: 'VARCHAR(255)', keboolaBaseType: 'STRING', nullable: true, description: '', length: '255' },
        { name: 'COUNTRY_ID', databaseNativeType: 'INTEGER', keboolaBaseType: 'INTEGER', nullable: true, description: '', length: null },
        { name: 'STATUS', databaseNativeType: 'VARCHAR(20)', keboolaBaseType: 'STRING', nullable: false, description: 'Active/Inactive status', length: '20' },
        { name: 'CREATED_DATE', databaseNativeType: 'DATE', keboolaBaseType: 'DATE', nullable: true, description: '', length: null },
      ],
      bucket: 'out.c-bdm',
      category: 'REF',
      lastImportDate: '2026-03-05T14:30:00Z',
    },
    {
      id: 'out.c-bdm.REF_PRODUCT',
      name: 'REF_PRODUCT',
      description: 'Product catalog reference data',
      primaryKey: ['PRODUCT_ID'],
      rowsCount: 3280,
      dataSizeBytes: 819200,
      columnCount: 5,
      columns: [
        { name: 'PRODUCT_ID', databaseNativeType: 'INTEGER', keboolaBaseType: 'INTEGER', nullable: false, description: 'Unique product identifier', length: null },
        { name: 'PRODUCT_NAME', databaseNativeType: 'VARCHAR(255)', keboolaBaseType: 'STRING', nullable: false, description: 'Product display name', length: '255' },
        { name: 'CATEGORY_ID', databaseNativeType: 'INTEGER', keboolaBaseType: 'INTEGER', nullable: true, description: '', length: null },
        { name: 'PRICE', databaseNativeType: 'DECIMAL(10,2)', keboolaBaseType: 'NUMERIC', nullable: true, description: 'Unit price', length: '10,2' },
        { name: 'IS_ACTIVE', databaseNativeType: 'BOOLEAN', keboolaBaseType: 'BOOLEAN', nullable: false, description: '', length: null },
      ],
      bucket: 'out.c-bdm',
      category: 'REF',
      lastImportDate: '2026-03-04T10:00:00Z',
    },
    {
      id: 'out.c-bdm.REF_COUNTRY',
      name: 'REF_COUNTRY',
      description: 'Country reference table',
      primaryKey: ['COUNTRY_ID'],
      rowsCount: 195,
      dataSizeBytes: 24576,
      columnCount: 3,
      columns: [
        { name: 'COUNTRY_ID', databaseNativeType: 'INTEGER', keboolaBaseType: 'INTEGER', nullable: false, description: 'Unique country identifier', length: null },
        { name: 'COUNTRY_NAME', databaseNativeType: 'VARCHAR(100)', keboolaBaseType: 'STRING', nullable: false, description: 'Country name', length: '100' },
        { name: 'COUNTRY_CODE', databaseNativeType: 'VARCHAR(3)', keboolaBaseType: 'STRING', nullable: false, description: 'ISO 3166 code', length: '3' },
      ],
      bucket: 'out.c-bdm',
      category: 'REF',
      lastImportDate: '2026-02-28T08:00:00Z',
    },
    {
      id: 'out.c-bdm.REF_CATEGORY',
      name: 'REF_CATEGORY',
      description: '',
      primaryKey: ['CATEGORY_ID'],
      rowsCount: 42,
      dataSizeBytes: 4096,
      columnCount: 2,
      columns: [
        { name: 'CATEGORY_ID', databaseNativeType: 'INTEGER', keboolaBaseType: 'INTEGER', nullable: false, description: '', length: null },
        { name: 'CATEGORY_NAME', databaseNativeType: 'VARCHAR(100)', keboolaBaseType: 'STRING', nullable: false, description: '', length: '100' },
      ],
      bucket: 'out.c-bdm',
      category: 'REF',
      lastImportDate: '2026-03-01T12:00:00Z',
    },
    {
      id: 'out.c-bdm.DIM_DATE',
      name: 'DIM_DATE',
      description: 'Date dimension with calendar attributes',
      primaryKey: ['DATE_ID'],
      rowsCount: 36500,
      dataSizeBytes: 5242880,
      columnCount: 6,
      columns: [
        { name: 'DATE_ID', databaseNativeType: 'DATE', keboolaBaseType: 'DATE', nullable: false, description: 'Date key', length: null },
        { name: 'YEAR', databaseNativeType: 'INTEGER', keboolaBaseType: 'INTEGER', nullable: false, description: '', length: null },
        { name: 'MONTH', databaseNativeType: 'INTEGER', keboolaBaseType: 'INTEGER', nullable: false, description: '', length: null },
        { name: 'DAY', databaseNativeType: 'INTEGER', keboolaBaseType: 'INTEGER', nullable: false, description: '', length: null },
        { name: 'QUARTER', databaseNativeType: 'INTEGER', keboolaBaseType: 'INTEGER', nullable: false, description: '', length: null },
        { name: 'DAY_OF_WEEK', databaseNativeType: 'VARCHAR(10)', keboolaBaseType: 'STRING', nullable: false, description: '', length: '10' },
      ],
      bucket: 'out.c-bdm',
      category: 'DIM',
      lastImportDate: '2026-03-06T00:00:00Z',
    },
    {
      id: 'out.c-bdm.DIM_STORE',
      name: 'DIM_STORE',
      description: '',
      primaryKey: ['STORE_ID'],
      rowsCount: 450,
      dataSizeBytes: 102400,
      columnCount: 4,
      columns: [
        { name: 'STORE_ID', databaseNativeType: 'INTEGER', keboolaBaseType: 'INTEGER', nullable: false, description: '', length: null },
        { name: 'STORE_NAME', databaseNativeType: 'VARCHAR(100)', keboolaBaseType: 'STRING', nullable: false, description: '', length: '100' },
        { name: 'COUNTRY_ID', databaseNativeType: 'INTEGER', keboolaBaseType: 'INTEGER', nullable: true, description: '', length: null },
        { name: 'OPENED_DATE', databaseNativeType: 'DATE', keboolaBaseType: 'DATE', nullable: true, description: '', length: null },
      ],
      bucket: 'out.c-bdm',
      category: 'DIM',
      lastImportDate: '2026-03-05T09:00:00Z',
    },
    {
      id: 'out.c-bdm.FCT_ORDER',
      name: 'FCT_ORDER',
      description: 'Fact table for customer orders',
      primaryKey: ['ORDER_ID'],
      rowsCount: 1250000,
      dataSizeBytes: 524288000,
      columnCount: 7,
      columns: [
        { name: 'ORDER_ID', databaseNativeType: 'INTEGER', keboolaBaseType: 'INTEGER', nullable: false, description: 'Unique order identifier', length: null },
        { name: 'CLIENT_ID', databaseNativeType: 'INTEGER', keboolaBaseType: 'INTEGER', nullable: false, description: 'FK to REF_CLIENT', length: null },
        { name: 'PRODUCT_ID', databaseNativeType: 'INTEGER', keboolaBaseType: 'INTEGER', nullable: false, description: '', length: null },
        { name: 'STORE_ID', databaseNativeType: 'INTEGER', keboolaBaseType: 'INTEGER', nullable: true, description: '', length: null },
        { name: 'ORDER_DATE', databaseNativeType: 'DATE', keboolaBaseType: 'DATE', nullable: false, description: 'Date of the order', length: null },
        { name: 'QUANTITY', databaseNativeType: 'INTEGER', keboolaBaseType: 'INTEGER', nullable: false, description: '', length: null },
        { name: 'TOTAL_AMOUNT', databaseNativeType: 'DECIMAL(12,2)', keboolaBaseType: 'NUMERIC', nullable: false, description: 'Order total in EUR', length: '12,2' },
      ],
      bucket: 'out.c-bdm',
      category: 'FCT',
      lastImportDate: '2026-03-06T06:00:00Z',
    },
    {
      id: 'out.c-bdm.FCT_PAYMENT',
      name: 'FCT_PAYMENT',
      description: 'Payment transactions linked to orders',
      primaryKey: ['PAYMENT_ID'],
      rowsCount: 890000,
      dataSizeBytes: 209715200,
      columnCount: 5,
      columns: [
        { name: 'PAYMENT_ID', databaseNativeType: 'INTEGER', keboolaBaseType: 'INTEGER', nullable: false, description: '', length: null },
        { name: 'ORDER_ID', databaseNativeType: 'INTEGER', keboolaBaseType: 'INTEGER', nullable: false, description: '', length: null },
        { name: 'PAYMENT_DATE', databaseNativeType: 'TIMESTAMP', keboolaBaseType: 'TIMESTAMP', nullable: false, description: '', length: null },
        { name: 'AMOUNT', databaseNativeType: 'DECIMAL(12,2)', keboolaBaseType: 'NUMERIC', nullable: false, description: '', length: '12,2' },
        { name: 'PAYMENT_METHOD', databaseNativeType: 'VARCHAR(30)', keboolaBaseType: 'STRING', nullable: true, description: '', length: '30' },
      ],
      bucket: 'out.c-bdm',
      category: 'FCT',
      lastImportDate: '2026-03-06T06:00:00Z',
    },
    {
      id: 'out.c-bdm.MAP_ORDER_PRODUCT',
      name: 'MAP_ORDER_PRODUCT',
      description: 'Mapping table between orders and products (line items)',
      primaryKey: ['ORDER_ID', 'PRODUCT_ID'],
      rowsCount: 3200000,
      dataSizeBytes: 419430400,
      columnCount: 4,
      columns: [
        { name: 'ORDER_ID', databaseNativeType: 'INTEGER', keboolaBaseType: 'INTEGER', nullable: false, description: '', length: null },
        { name: 'PRODUCT_ID', databaseNativeType: 'INTEGER', keboolaBaseType: 'INTEGER', nullable: false, description: '', length: null },
        { name: 'QUANTITY', databaseNativeType: 'INTEGER', keboolaBaseType: 'INTEGER', nullable: false, description: '', length: null },
        { name: 'LINE_TOTAL', databaseNativeType: 'DECIMAL(10,2)', keboolaBaseType: 'NUMERIC', nullable: false, description: '', length: '10,2' },
      ],
      bucket: 'out.c-bdm',
      category: 'MAP',
      lastImportDate: '2026-03-06T06:00:00Z',
    },
    {
      id: 'out.c-bdm_aux.AUX_STAGING_ORDERS',
      name: 'AUX_STAGING_ORDERS',
      description: '',
      primaryKey: [],
      rowsCount: 0,
      dataSizeBytes: 0,
      columnCount: 3,
      columns: [
        { name: 'RAW_DATA', databaseNativeType: 'VARCHAR(16777216)', keboolaBaseType: 'STRING', nullable: true, description: '', length: null },
        { name: 'SOURCE', databaseNativeType: 'VARCHAR(50)', keboolaBaseType: 'STRING', nullable: true, description: '', length: '50' },
        { name: 'LOADED_AT', databaseNativeType: 'TIMESTAMP', keboolaBaseType: 'TIMESTAMP', nullable: true, description: '', length: null },
      ],
      bucket: 'out.c-bdm_aux',
      category: 'AUX',
      lastImportDate: null,
    },
  ];

  const edges = [
    { id: 'FCT_ORDER.CLIENT_ID→REF_CLIENT', source: 'FCT_ORDER', target: 'REF_CLIENT', sourceColumn: 'CLIENT_ID', targetColumn: 'CLIENT_ID', label: 'CLIENT', cardinality: 'M:1', inferenceMethod: 'direct' },
    { id: 'FCT_ORDER.PRODUCT_ID→REF_PRODUCT', source: 'FCT_ORDER', target: 'REF_PRODUCT', sourceColumn: 'PRODUCT_ID', targetColumn: 'PRODUCT_ID', label: 'PRODUCT', cardinality: 'M:1', inferenceMethod: 'direct' },
    { id: 'FCT_ORDER.STORE_ID→DIM_STORE', source: 'FCT_ORDER', target: 'DIM_STORE', sourceColumn: 'STORE_ID', targetColumn: 'STORE_ID', label: 'STORE', cardinality: 'M:1', inferenceMethod: 'direct' },
    { id: 'FCT_PAYMENT.ORDER_ID→FCT_ORDER', source: 'FCT_PAYMENT', target: 'FCT_ORDER', sourceColumn: 'ORDER_ID', targetColumn: 'ORDER_ID', label: 'ORDER', cardinality: 'M:1', inferenceMethod: 'direct' },
    { id: 'MAP_ORDER_PRODUCT.ORDER_ID→FCT_ORDER', source: 'MAP_ORDER_PRODUCT', target: 'FCT_ORDER', sourceColumn: 'ORDER_ID', targetColumn: 'ORDER_ID', label: 'ORDER', cardinality: 'M:1', inferenceMethod: 'direct' },
    { id: 'MAP_ORDER_PRODUCT.PRODUCT_ID→REF_PRODUCT', source: 'MAP_ORDER_PRODUCT', target: 'REF_PRODUCT', sourceColumn: 'PRODUCT_ID', targetColumn: 'PRODUCT_ID', label: 'PRODUCT', cardinality: 'M:1', inferenceMethod: 'direct' },
    { id: 'REF_CLIENT.COUNTRY_ID→REF_COUNTRY', source: 'REF_CLIENT', target: 'REF_COUNTRY', sourceColumn: 'COUNTRY_ID', targetColumn: 'COUNTRY_ID', label: 'COUNTRY', cardinality: 'M:1', inferenceMethod: 'direct' },
    { id: 'REF_PRODUCT.CATEGORY_ID→REF_CATEGORY', source: 'REF_PRODUCT', target: 'REF_CATEGORY', sourceColumn: 'CATEGORY_ID', targetColumn: 'CATEGORY_ID', label: 'CATEGORY', cardinality: 'M:1', inferenceMethod: 'direct' },
    { id: 'DIM_STORE.COUNTRY_ID→REF_COUNTRY', source: 'DIM_STORE', target: 'REF_COUNTRY', sourceColumn: 'COUNTRY_ID', targetColumn: 'COUNTRY_ID', label: 'COUNTRY', cardinality: 'M:1', inferenceMethod: 'direct' },
  ];

  const dateEdges = [
    { id: 'date:FCT_ORDER.ORDER_DATE→DIM_DATE', source: 'FCT_ORDER', target: 'DIM_DATE', sourceColumn: 'ORDER_DATE', targetColumn: 'DATE_ID', label: 'ORDER_DATE', cardinality: 'M:1', inferenceMethod: 'date-assumed' },
    { id: 'date:FCT_PAYMENT.PAYMENT_DATE→DIM_DATE', source: 'FCT_PAYMENT', target: 'DIM_DATE', sourceColumn: 'PAYMENT_DATE', targetColumn: 'DATE_ID', label: 'PAYMENT_DATE', cardinality: 'M:1', inferenceMethod: 'date-assumed' },
    { id: 'date:REF_CLIENT.CREATED_DATE→DIM_DATE', source: 'REF_CLIENT', target: 'DIM_DATE', sourceColumn: 'CREATED_DATE', targetColumn: 'DATE_ID', label: 'CREATED_DATE', cardinality: 'M:1', inferenceMethod: 'date-assumed' },
    { id: 'date:DIM_STORE.OPENED_DATE→DIM_DATE', source: 'DIM_STORE', target: 'DIM_DATE', sourceColumn: 'OPENED_DATE', targetColumn: 'DATE_ID', label: 'OPENED_DATE', cardinality: 'M:1', inferenceMethod: 'date-assumed' },
  ];

  const categories = {};
  for (const t of tables) {
    categories[t.name] = t.category;
  }

  return {
    tables,
    edges,
    dateEdges,
    categories,
    lastRefresh: new Date().toISOString(),
    stats: {
      totalColumns: tables.reduce((acc, t) => acc + t.columns.length, 0),
      idColumns: 12,
      matched: 9,
      skipped: 0,
      aliased: 0,
      unmatched: 1,
      selfRefSkipped: 6,
    },
  };
}
